[features]
seeds = true
skip-lint = false
[programs.localnet]
tinydancer_program_library = "8iRs7VTbXwErab5vUjRH1tzJoUKLJpe2crYPXMZQKFpR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/anoushk/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
