[package]
name = "jito-geyser-protos"
version = "0.1.0"
authors = ["Jito Foundation <team@jito.network>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
prost = "0.11.6"
prost-types = "0.11.6"
serde = "1.0.152"
solana-account-decoder = "=1.14.13"
solana-sdk = "=1.14.13"
solana-transaction-status = "=1.14.13"
tonic = "0.8.3"
# jito-solana-sdk = { git = "https://github.com/jito-foundation/jito-solana.git", tag = "v1.14.13-jito", package = "solana-sdk"  }
# jito-solana-transaction-status = { git = "https://github.com/jito-foundation/jito-solana.git", tag = "v1.14.13-jito", package = "solana-transaction-status"  }
# jito-solana-account-decoder = { git = "https://github.com/jito-foundation/jito-solana.git", tag = "v1.14.13-jito", package = "solana-account-decoder"  }

[build-dependencies]
tonic-build = "0.8.4"

# [features]
# jito-solana = ["jito-solana-sdk", "jito-solana-transaction-status", "jito-solana-account-decoder"]
